### PR TITLE
Updated to rules as of April 28th, 2016

### PR DESCRIPTION
**Pull request by crstamps2**
Just updating the regex's to match today's rules as described here: https://ntsi.com/drivers-license-format/

If approved, can you also go ahead and release the updated gem to rubygems?

### CODE REVIEW

**Comment by amedeiros** [comment]
I will try and take a look at the pull request either this weekend or Monday.

**Comment by amedeiros** [comment]
👍 Looks good to me.

**Comment by crstamps2** [comment]
Thanks @amedeiros . and the resulting gem was pushed to rubygems?

**Comment by cody-homedepot** [comment]
@amedeiros can you push the newest version of the gem to rubygems?

**Comment by amedeiros** [comment]
@cody-homedepot I can upload the new gem. I actually meant to and completely forgot sorry about that. I also added you to the contributors section of the read me hope thats ok with you.

**Comment by amedeiros** [comment]
@cody-homedepot new gem is out. Thank you!

**Comment by crstamps2** [comment]
That's awesome. Thanks!

**Pull request merged**
