### PR TITLE
changed gsub to allow asterisks so that washington can be validated

### PR DESCRIPTION
**Pull request by jonsgreene**
also added test to verify that the asterisk will be included for validation.

### CODE REVIEW

**Comment by amedeiros** [comment]
Looks good to me. Washington supports asterisks in their drivers licenses?

**Comment by amedeiros** [comment]
I'm going to merge this and release on Monday.

**Comment by jonsgreene** [comment]
Yeah they sure do. Thanks for accepting the changes

**Comment by amedeiros** [comment]
https://rubygems.org/gems/dl_validator/versions/0.0.7

Got this out later than expected. Thank you for the fix!

**Pull request merged**
